#@data/values
---
svc_port: 80
app_port: 80
hello_msg: stranger

#! Optionally specify image repo to push image to.
#! If not specified, image will not be pushed to a registry
#! (e.g. "docker.io/dkalinin/k8s-simple-app")
push_images_repo: ""
